### ISSUE TITLE
Question regarding bundling for Xcode

### ISSUE THREAD

**Issue by sebleclerc** [jarroyoesp/KotlinMultiPlatform#4]
First of all, a big thanks! I had all the problem in the world to have my setting complete with the iOS portion. My Android app is running fine wit the shared code but noting worked with iOS. I did checked how you configured everything and use the same approach and now everything seems to be working fine.

Now, I have a question related to the bundling of Kotlin code into the iOS framework. I thought the iOS project had to import the `.framework` to be able to use the code. Now after building and using the `packForXcode` task in a script phase, the code is just magically there to be imported. Do you know what is going on exactly?

Thanks!

**Comment by jarroyoesp** [comment]
Hi Sébastien,
Thank you for the question. If you open the Xcode project and navigate to "BuildPhases", in this section, if you open "Run Script" you can see how you import the .framwework.

```
"$SRCROOT/../gradlew" -p "$SRCROOT/../SharedCode" packForXCode \
-Pconfiguration.build.dir="$CONFIGURATION_BUILD_DIR"          \
-Pkotlin.build.type="$KOTLIN_BUILD_TYPE"                      \
-Pdevice="$KOTLIN_DEVICE"
```
Be careful when you create a new project on XCode, move this new Build Phase to the top of the list.

Here you can see more in details how it works: https://play.kotlinlang.org/hands-on/Targeting%20iOS%20and%20Android%20with%20Kotlin%20Multiplatform/06_SettingUpKotlinFramework

I hope it helps you!

**Comment by sebleclerc** [comment]
I had already put it on top of the build phases 😄 Thanks for you answer!
